imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    # connection parameters
    rabbitmq_connections:
        default: { host: 'localhost', port: 5672, user: 'guest', password: 'guest', vhost: '/' }

    # define producers
    rabbitmq_producers:
        test:
            connection:         default
            exchange_options:   {name: 'test', type: direct}

    # define consumers
    rabbitmq_consumers:
        test:
            connection:         default
            exchange_options:   {name: 'test', type: direct}
            queue_options:      {name: 'test'}
            callback:           rabbitmq.callback.service

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    serializer:
        enabled: true
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [masterofcodeBundle]
    assets:
        font-bootstrap-1:
            inputs: '%kernel.root_dir%/../src/masterofcodeBundle/Resources/public/fonts/glyphicons-halflings-regular.woff'
            output: 'fonts/glyphicons-halflings-regular.woff'
        font-bootstrap-2:
            inputs: '%kernel.root_dir%/../src/masterofcodeBundle/Resources/public/fonts/glyphicons-halflings-regular.woff2'
            output: 'fonts/glyphicons-halflings-regular.woff2'
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

old_sound_rabbit_mq:
    connections: %rabbitmq_connections%
    producers: %rabbitmq_producers%
    consumers: %rabbitmq_consumers%

services:
    rabbitmq.callback.service:
        class: masterofcodeBundle\Command\ConvertCommand
        arguments:
            entityManager: "@doctrine.orm.entity_manager"